--@TODO move this logic to migration instead of CZ

INSERT INTO category (id, name, is_root, parent_id, slug) VALUES
(1, 'Art', FALSE, -1, 'art'),
(3, 'Comics', FALSE, -1, 'comics'),
(6, 'Dance', FALSE, -1, 'dance'),
(7, 'Design', FALSE, -1, 'design'),
(9, 'Fashion', FALSE, -1, 'fashion'),
(10, 'Food', FALSE, -1, 'food'),
(11, 'Film & Video', FALSE, -1, 'film & video'),
(12, 'Games', FALSE, -1, 'games'),
(13, 'Journalism', FALSE, -1, 'journalism'),
(14, 'Music', FALSE, -1, 'music'),
(15, 'Photography', FALSE, -1, 'photography'),
(16, 'Technology', FALSE, -1, 'technology'),
(17, 'Theater', FALSE, -1, 'theater'),
(18, 'Publishing', FALSE, -1, 'publishing'),
(26, 'Crafts', FALSE, -1, 'crafts');

INSERT INTO category (id, name, is_root, parent_id, slug) VALUES
(20, 'Conceptual Art', TRUE, 1, 'art/conceptual art'),
(21, 'Digital Art', TRUE, 1, 'art/digital art'),
(22, 'Illustration', TRUE, 1, 'art/illustration'),
(23, 'Painting', TRUE, 1, 'art/painting'),
(24, 'Performance Art', TRUE, 1, 'art/performance art'),
(25, 'Sculpture', TRUE, 1, 'art/sculpture'),
(27, 'Graphic Design', TRUE, 7, 'design/graphic design'),
(28, 'Product Design', TRUE, 7, 'design/product design'),
(29, 'Animation', TRUE, 11, 'film & video/animation'),
(30, 'Documentary', TRUE, 11, 'film & video/documentary'),
(31, 'Narrative Film', TRUE, 11, 'film & video/narrative film'),
(32, 'Shorts', TRUE, 11, 'film & video/shorts'),
(33, 'Webseries', TRUE, 11, 'film & video/webseries'),
(34, 'Tabletop Games', TRUE, 12, 'games/tabletop games'),
(35, 'Video Games', TRUE, 12, 'games/video games'),
(36, 'Classical Music', TRUE, 14, 'music/classical music'),
(37, 'Country & Folk', TRUE, 14, 'music/country & folk'),
(38, 'Electronic Music', TRUE, 14, 'music/electronic music'),
(39, 'Hip-Hop', TRUE, 14, 'music/hip-hop'),
(40, 'Indie Rock', TRUE, 14, 'music/indie rock'),
(41, 'Jazz', TRUE, 14, 'music/jazz'),
(42, 'Pop', TRUE, 14, 'music/pop'),
(43, 'Rock', TRUE, 14, 'music/rock'),
(44, 'World Music', TRUE, 14, 'music/world music'),
(45, 'Art Books', TRUE, 18, 'publishing/art books'),
(46, 'Children''s Books', TRUE, 18, 'publishing/children''s books'),
(47, 'Fiction', TRUE, 18, 'publishing/fiction'),
(48, 'Nonfiction', TRUE, 18, 'publishing/nonfiction'),
(49, 'Periodicals', TRUE, 18, 'publishing/periodicals'),
(50, 'Poetry', TRUE, 18, 'publishing/poetry'),
(51, 'Software', TRUE, 16, 'technology/software'),
(52, 'Hardware', TRUE, 16, 'technology/hardware'),
(53, 'Public Art', TRUE, 1, 'art/public art'),
(54, 'Mixed Media', TRUE, 1, 'art/mixed media'),
(239, 'Radio & Podcasts', TRUE, 18, 'publishing/radio & podcasts'),
(241, 'Metal', TRUE, 14, 'music/metal'),
(249, 'Anthologies', TRUE, 3, 'comics/anthologies'),
(250, 'Comic Books', TRUE, 3, 'comics/comic books'),
(251, 'Events', TRUE, 3, 'comics/events'),
(252, 'Graphic Novels', TRUE, 3, 'comics/graphic novels'),
(253, 'Webcomics', TRUE, 3, 'comics/webcomics'),
(254, 'Performances', TRUE, 6, 'dance/performances'),
(255, 'Residencies', TRUE, 6, 'dance/residencies'),
(256, 'Spaces', TRUE, 6, 'dance/spaces'),
(257, 'Workshops', TRUE, 6, 'dance/workshops'),
(258, 'Architecture', TRUE, 7, 'design/architecture'),
(259, 'Civic Design', TRUE, 7, 'design/civic design'),
(260, 'Interactive Design', TRUE, 7, 'design/interactive design'),
(261, 'Typography', TRUE, 7, 'design/typography'),
(262, 'Accessories', TRUE, 9, 'fashion/accessories'),
(263, 'Apparel', TRUE, 9, 'fashion/apparel'),
(264, 'Childrenswear', TRUE, 9, 'fashion/childrenswear'),
(265, 'Couture', TRUE, 9, 'fashion/couture'),
(266, 'Footwear', TRUE, 9, 'fashion/footwear'),
(267, 'Jewelry', TRUE, 9, 'fashion/jewelry'),
(268, 'Pet Fashion', TRUE, 9, 'fashion/pet fashion'),
(269, 'Ready-to-wear', TRUE, 9, 'fashion/ready-to-wear'),
(270, 'Gaming Hardware', TRUE, 12, 'games/gaming hardware'),
(271, 'Live Games', TRUE, 12, 'games/live games'),
(272, 'Mobile Games', TRUE, 12, 'games/mobile games'),
(273, 'Playing Cards', TRUE, 12, 'games/playing cards'),
(274, 'Puzzles', TRUE, 12, 'games/puzzles'),
(275, 'Animals', TRUE, 15, 'photography/animals'),
(276, 'Fine Art', TRUE, 15, 'photography/fine art'),
(277, 'Nature', TRUE, 15, 'photography/nature'),
(278, 'People', TRUE, 15, 'photography/people'),
(279, 'Places', TRUE, 15, 'photography/places'),
(280, 'Photobooks', TRUE, 15, 'photography/photobooks'),
(281, 'Experimental', TRUE, 17, 'theater/experimental'),
(282, 'Festivals', TRUE, 17, 'theater/festivals'),
(283, 'Immersive', TRUE, 17, 'theater/immersive'),
(284, 'Musical', TRUE, 17, 'theater/musical'),
(285, 'Plays', TRUE, 17, 'theater/plays'),
(286, 'Spaces', TRUE, 17, 'theater/spaces'),
(287, 'Ceramics', TRUE, 1, 'art/ceramics'),
(288, 'Installations', TRUE, 1, 'art/installations'),
(289, 'Textiles', TRUE, 1, 'art/textiles'),
(290, 'Video Art', TRUE, 1, 'art/video art'),
(291, 'Action', TRUE, 11, 'film & video/action'),
(292, 'Comedy', TRUE, 11, 'film & video/comedy'),
(293, 'Drama', TRUE, 11, 'film & video/drama'),
(294, 'Experimental', TRUE, 11, 'film & video/experimental'),
(295, 'Festivals', TRUE, 11, 'film & video/festivals'),
(296, 'Fantasy', TRUE, 11, 'film & video/fantasy'),
(297, 'Horror', TRUE, 11, 'film & video/horror'),
(298, 'Movie Theaters', TRUE, 11, 'film & video/movie theaters'),
(299, 'Music Videos', TRUE, 11, 'film & video/music videos'),
(300, 'Romance', TRUE, 11, 'film & video/romance'),
(301, 'Science Fiction', TRUE, 11, 'film & video/science fiction'),
(302, 'Thrillers', TRUE, 11, 'film & video/thrillers'),
(303, 'Television', TRUE, 11, 'film & video/television'),
(304, 'Bacon', TRUE, 10, 'food/bacon'),
(305, 'Community Gardens', TRUE, 10, 'food/community gardens'),
(306, 'Cookbooks', TRUE, 10, 'food/cookbooks'),
(307, 'Drinks', TRUE, 10, 'food/drinks'),
(308, 'Events', TRUE, 10, 'food/events'),
(309, 'Farms', TRUE, 10, 'food/farms'),
(310, 'Farmer''s Markets', TRUE, 10, 'food/farmer''s markets'),
(311, 'Food Trucks', TRUE, 10, 'food/food trucks'),
(312, 'Restaurants', TRUE, 10, 'food/restaurants'),
(313, 'Small Batch', TRUE, 10, 'food/small batch'),
(314, 'Spaces', TRUE, 10, 'food/spaces'),
(315, 'Vegan', TRUE, 10, 'food/vegan'),
(316, 'Blues', TRUE, 14, 'music/blues'),
(317, 'Chiptune', TRUE, 14, 'music/chiptune'),
(318, 'Faith', TRUE, 14, 'music/faith'),
(319, 'Kids', TRUE, 14, 'music/kids'),
(320, 'Latin', TRUE, 14, 'music/latin'),
(321, 'Punk', TRUE, 14, 'music/punk'),
(322, 'R&B', TRUE, 14, 'music/r&b'),
(323, 'Academic', TRUE, 18, 'publishing/academic'),
(324, 'Anthologies', TRUE, 18, 'publishing/anthologies'),
(325, 'Calendars', TRUE, 18, 'publishing/calendars'),
(326, 'Literary Journals', TRUE, 18, 'publishing/literary journals'),
(327, 'Translations', TRUE, 18, 'publishing/translations'),
(328, 'Young Adult', TRUE, 18, 'publishing/young adult'),
(329, 'Zines', TRUE, 18, 'publishing/zines'),
(330, 'Family', TRUE, 11, 'film & video/family'),
(331, '3D Printing', TRUE, 16, 'technology/3d printing'),
(332, 'Apps', TRUE, 16, 'technology/apps'),
(333, 'Camera Equipment', TRUE, 16, 'technology/camera equipment'),
(334, 'DIY Electronics', TRUE, 16, 'technology/diy electronics'),
(335, 'Fabrication Tools', TRUE, 16, 'technology/fabrication tools'),
(336, 'Flight', TRUE, 16, 'technology/flight'),
(337, 'Gadgets', TRUE, 16, 'technology/gadgets'),
(338, 'Robots', TRUE, 16, 'technology/robots'),
(339, 'Sound', TRUE, 16, 'technology/sound'),
(340, 'Space Exploration', TRUE, 16, 'technology/space exploration'),
(341, 'Wearables', TRUE, 16, 'technology/wearables'),
(342, 'Web', TRUE, 16, 'technology/web'),
(343, 'Candles', TRUE, 26, 'crafts/candles'),
(344, 'Crochet', TRUE, 26, 'crafts/crochet'),
(345, 'DIY', TRUE, 26, 'crafts/diy'),
(346, 'Embroidery', TRUE, 26, 'crafts/embroidery'),
(347, 'Glass', TRUE, 26, 'crafts/glass'),
(348, 'Knitting', TRUE, 26, 'crafts/knitting'),
(349, 'Letterpress', TRUE, 18, 'publishing/letterpress'),
(350, 'Pottery', TRUE, 26, 'crafts/pottery'),
(351, 'Printing', TRUE, 26, 'crafts/printing'),
(352, 'Quilts', TRUE, 26, 'crafts/quilts'),
(353, 'Stationery', TRUE, 26, 'crafts/stationery'),
(354, 'Taxidermy', TRUE, 26, 'crafts/taxidermy'),
(355, 'Weaving', TRUE, 26, 'crafts/weaving'),
(356, 'Woodworking', TRUE, 26, 'crafts/woodworking'),
(357, 'Audio', TRUE, 13, 'journalism/audio'),
(358, 'Photo', TRUE, 13, 'journalism/photo'),
(359, 'Print', TRUE, 13, 'journalism/print'),
(360, 'Video', TRUE, 13, 'journalism/video'),
(361, 'Web', TRUE, 13, 'journalism/web'),
(362, 'Makerspaces', TRUE, 16, 'technology/makerspaces'),
(386, 'Comedy', TRUE, 14, 'music/comedy'),
(387, 'Comedy', TRUE, 18, 'publishing/comedy'),
(388, 'Comedy', TRUE, 17, 'theater/comedy'),
(389, 'Literary Spaces', TRUE, 18, 'publishing/literary spaces');