--@TODO deal with roles (reader, writer/admin)?

CREATE TABLE project (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	name varchar(255) NOT NULL,
	description varchar(255) NOT NULL,
	url varchar(512) NOT NULL,
	deadline DATE
);

CREATE TABLE project_photo (
    project_id BIGINT IDENTITY,
    thumb varchar(512),
	small varchar(512),
	CONSTRAINT fk_project_photo_project_id FOREIGN KEY(project_id) REFERENCES project(id)
);

-- @TODO - email must be unique
CREATE TABLE user (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	email varchar (255),
	name varchar (255) NOT NULL,
	surname varchar (255) NOT NULL
);

CREATE TABLE `group` (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    leader_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    name varchar (255) NOT NULL,
    CONSTRAINT fk_group_leader_id FOREIGN KEY(leader_id) REFERENCES user(id),
    CONSTRAINT fk_group_project_id FOREIGN KEY(project_id) REFERENCES project(id)
);

CREATE TABLE user_2_group (
    group_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL
);

CREATE TABLE user_auth (
    user_id BIGINT IDENTITY,
    name varchar (255),
    password varchar (255),
    CONSTRAINT fk_user_auth_user_id FOREIGN KEY(user_id) REFERENCES user(id)
);
